# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from resources import face_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(764, 596)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/android.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-image: url(:/background/background.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 281, 51))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-image: url(:/label/transparent.jpg);")
        self.label.setObjectName("label")
        self.faceView = QtWidgets.QLabel(self.centralwidget)
        self.faceView.setGeometry(QtCore.QRect(60, 190, 291, 221))
        self.faceView.setStyleSheet("background-image: url(:/imageView/face.jpg);")
        self.faceView.setText("")
        self.faceView.setObjectName("faceView")
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(80, 430, 261, 61))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.infoLabel.setFont(font)
        self.infoLabel.setStyleSheet("background-image: url(:/label/transparent.jpg);")
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(520, 190, 141, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.admainButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.admainButton.setFont(font)
        self.admainButton.setStyleSheet("background-image: url(:/label/transparent.jpg);")
        self.admainButton.setIcon(icon)
        self.admainButton.setObjectName("admainButton")
        self.verticalLayout.addWidget(self.admainButton)
        self.cameraButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.cameraButton.setFont(font)
        self.cameraButton.setStyleSheet("background-image: url(:/label/transparent.jpg);")
        self.cameraButton.setIcon(icon)
        self.cameraButton.setObjectName("cameraButton")
        self.verticalLayout.addWidget(self.cameraButton)
        self.ImageButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.ImageButton.setFont(font)
        self.ImageButton.setStyleSheet("background-image: url(:/label/transparent.jpg);")
        self.ImageButton.setIcon(icon)
        self.ImageButton.setObjectName("ImageButton")
        self.verticalLayout.addWidget(self.ImageButton)
        self.statisButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.statisButton.setFont(font)
        self.statisButton.setStyleSheet("background-image: url(:/label/transparent.jpg);")
        self.statisButton.setIcon(icon)
        self.statisButton.setObjectName("statisButton")
        self.verticalLayout.addWidget(self.statisButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.ImageButton.clicked.connect(MainWindow.showFace)
        self.cameraButton.clicked.connect(MainWindow.showCamera)
        self.admainButton.clicked.connect(MainWindow.showAdmain)
        self.statisButton.clicked.connect(MainWindow.showStatis)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人脸识别打卡系统"))
        self.label.setText(_translate("MainWindow", "人脸识别打卡系统"))
        self.admainButton.setText(_translate("MainWindow", "用户管理"))
        self.cameraButton.setText(_translate("MainWindow", "人脸识别"))
        self.ImageButton.setText(_translate("MainWindow", "人脸匹配"))
        self.statisButton.setText(_translate("MainWindow", "打卡统计"))
